# Generated by Django 3.1 on 2020-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('email_id', models.EmailField(max_length=50)),
                ('branch', models.TextField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
