# Generated by Django 3.1 on 2020-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201125_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('culture_name', models.TextField()),
                ('r_fees', models.FloatField()),
                ('date_of_event', models.DateTimeField()),
                ('venue', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
