# Generated by Django 3.1 on 2020-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_cultural_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultural',
            name='culture_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cultural',
            name='details',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cultural',
            name='venue',
            field=models.TextField(max_length=50),
        ),
    ]
