# Generated by Django 3.1 on 2020-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmental',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_id', models.IntegerField()),
                ('subevent_name', models.TextField(max_length=50)),
                ('r_fees', models.FloatField()),
                ('date_of_event', models.DateTimeField()),
                ('venue', models.TextField(max_length=50)),
                ('details', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.TextField(max_length=20)),
                ('dept_event_name', models.TextField(max_length=20)),
            ],
        ),
    ]
