# Generated by Django 3.1 on 2020-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_dept_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmental',
            name='event_poster',
            field=models.TextField(default='insync.jpg', max_length=20),
            preserve_default=False,
        ),
    ]
